version: '3'

services:
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../:/var/www/html
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - php
      - postgres
  php:
    build: ./php
    container_name: php
    restart: always
    volumes:
      - ./../:/var/www/html
  composer:
    image: composer
    container_name: composer
    volumes:
      - ./../:/app
    command: install
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
